spring:
  application:
    name: CONFIG-SERVER


eureka:
  client:
    hostname: 172.16.5.210
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://172.16.5.210:8761/eureka/
   instance:
    hostname: 172.16.5.210

